### ISSUE TITLE
add compiled hw file

### ISSUE THREAD

**Issue by dmcglinn** [kelseymartin1/Assignments#1]
Nice job getting this setup @kelseymartin1 please just add either an html or pdf version of your compiled code. Thanks!

**Comment by kelseymartin1** [comment]
I'm not sure why, but when I add my .html file, it uploads a huge file that is completely different from my assignment.

**Comment by dmcglinn** [comment]
take a look this from the past commit you put up- it looks great - just post the .html file you had before

https://htmlpreview.github.io/?
https://github.com/kelseymartin1/Assignments/blob/f23bab4d7b58a9784503acb395279350978c3638/Assignment_2.html

**Comment by dmcglinn** [comment]
sorry bad link
https://htmlpreview.github.io/?https://github.com/kelseymartin1/Assignments/blob/f23bab4d7b58a9784503acb395279350978c3638/Assignment_2.html
